### ISSUE TITLE
this.setState is not a function

### ISSUE THREAD

**Issue by zetay** [atomicojs/core#6]
I'm using atomico@0.7.3, and compiled by webpack@4 with config below

`{
            test: /\.(js|jsx|mjs)$/,
            //include: paths.appSrc,
            loader: require.resolve('babel-loader'),
            options: {
              presets: [
                [
                  '@babel/preset-env',
                  {
                    targets: 'chrome >= 57'
                  }
                ],
                [
                  '@babel/preset-react',
                  {
                    pragma: 'h'
                  }
                ]
              ],
              plugins: [
                '@babel/plugin-proposal-class-properties',
                [
                  '@babel/plugin-proposal-decorators',
                  {
                    legacy: true
                  }
                ],
                '@babel/plugin-proposal-function-bind',
                '@babel/plugin-proposal-object-rest-spread',
                '@babel/plugin-syntax-dynamic-import'
              ],
              // This is a feature of `babel-loader` for webpack (not Babel itself).
              // It enables caching results in ./node_modules/.cache/babel-loader/
              // directory for faster rebuilds.
              cacheDirectory: true
            }`

**Comment by UpperCod** [comment]
I appreciate the fact that I have tried Atomico, but I want to inform you that it has been restarted, now the approach is functional, I invite you to see the [latest release](https://github.com/atomicojs/core/releases)
